// <auto-generated />
namespace ТриКлика.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class priceFix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(priceFix));
        
        string IMigrationMetadata.Id
        {
            get { return "202309032056465_priceFix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
